(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments mk_ref {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | mk_ref x => x
  end.

Parameter n: Z.

Axiom H : (0%Z <= n)%Z.

Parameter r: Z.

Parameter i: Z.

Axiom H1 : (r = (i * (i + 1%Z)%Z)%Z).

Axiom H2 : (0%Z <= i)%Z.

Axiom H3 : (i < n)%Z.

Parameter i1: Z.

Axiom H4 : (i1 = (i + 1%Z)%Z).

Parameter r1: Z.

Axiom H5 : (r1 = (r + i1)%Z).

(* Why3 goal *)
Theorem VC_somme : (r1 = (i1 * (i1 + 1%Z)%Z)%Z) /\ (0%Z <= i1)%Z.
Proof.


Qed.

